# Fill Missing Values

In [2]:
import pandas as pd

In [3]:
# Load Titanic dataset
# loaded the Titanic dataset into a DataFrame (df)
df = pd.read_csv('titanic.csv')

In [5]:
df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Survived
0,1,3,Allison Hill,male,17,4,2,43d75413-a939-4bd1-a516-b0d47d3572cc,144.08,Q,1
1,2,1,Noah Rhodes,male,60,2,2,6334fa2a-8b4b-47e7-a451-5ae01754bf08,249.04,S,0
2,3,3,Angie Henderson,male,64,0,0,61a66444-e2af-4629-9efb-336e2f546033,50.31,Q,1
3,4,3,Daniel Wagner,male,35,4,0,0b6c03c8-721e-4419-afc3-e6495e911b91,235.20,C,1
4,5,1,Cristian Santos,female,70,0,3,436e3c49-770e-49db-b092-d40143675d58,160.17,C,1

In [6]:
# Fill missing values in 'Age' column with the median
df['Age'] = df['Age'].fillna(df['Age'].median())

In [7]:
df['Age'].head()

0    17
1    60
2    64
3    35
4    70
Name: Age, dtype: int64

In [8]:
# Fill missing values in categorical columns with the mode
categorical_columns = df.select_dtypes(include=['object']).columns

In [10]:
categorical_columns

Index(['Name', 'Sex', 'Ticket', 'Embarked'], dtype='object')

In [12]:
for col in categorical_columns:
    df[col] = df[col].fillna(df[col].mode()[0])

In [13]:
 df[col].head()

0    Q
1    S
2    Q
3    C
4    C
Name: Embarked, dtype: object

In [15]:
# Check if there are any missing values left
df.isnull().sum()

PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
Survived       0
dtype: int64

# One-Hot Encoding and Label Encoding

In [16]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [17]:
# Load Titanic dataset
# loaded the Titanic dataset into a DataFrame (df)
df = pd.read_csv('titanic.csv')

In [21]:
# Displaying the first few rows to understand the dataset
df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Survived
0,1,3,Allison Hill,male,17,4,2,43d75413-a939-4bd1-a516-b0d47d3572cc,144.08,Q,1
1,2,1,Noah Rhodes,male,60,2,2,6334fa2a-8b4b-47e7-a451-5ae01754bf08,249.04,S,0
2,3,3,Angie Henderson,male,64,0,0,61a66444-e2af-4629-9efb-336e2f546033,50.31,Q,1
3,4,3,Daniel Wagner,male,35,4,0,0b6c03c8-721e-4419-afc3-e6495e911b91,235.20,C,1
4,5,1,Cristian Santos,female,70,0,3,436e3c49-770e-49db-b092-d40143675d58,160.17,C,1

In [22]:
# Identifying categorical variables
categorical_columns = ['Sex', 'Embarked', 'Pclass']

In [23]:
categorical_columns

['Sex', 'Embarked', 'Pclass']

In [25]:
# One-Hot Encoding for 'Sex' and 'Embarked'
titanic_df_encoded = pd.get_dummies(df, columns=['Sex', 'Embarked'], drop_first=True)

In [27]:
titanic_df_encoded.head()

,PassengerId,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Survived,Sex_male,Embarked_Q,Embarked_S
0,1,3,Allison Hill,17,4,2,43d75413-a939-4bd1-a516-b0d47d3572cc,144.08,1,True,True,False
1,2,1,Noah Rhodes,60,2,2,6334fa2a-8b4b-47e7-a451-5ae01754bf08,249.04,0,True,False,True
2,3,3,Angie Henderson,64,0,0,61a66444-e2af-4629-9efb-336e2f546033,50.31,1,True,True,False
3,4,3,Daniel Wagner,35,4,0,0b6c03c8-721e-4419-afc3-e6495e911b91,235.20,1,True,False,False
4,5,1,Cristian Santos,70,0,3,436e3c49-770e-49db-b092-d40143675d58,160.17,1,False,False,False

In [28]:
# Label Encoding for 'Pclass'
label_encoder = LabelEncoder()
titanic_df_encoded['Pclass'] = label_encoder.fit_transform(titanic_df_encoded['Pclass'])

In [30]:
titanic_df_encoded['Pclass'].head()

0    2
1    0
2    2
3    2
4    0
Name: Pclass, dtype: int64

In [31]:
# Display the resulting DataFrame
(titanic_df_encoded.head())

,PassengerId,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Survived,Sex_male,Embarked_Q,Embarked_S
0,1,2,Allison Hill,17,4,2,43d75413-a939-4bd1-a516-b0d47d3572cc,144.08,1,True,True,False
1,2,0,Noah Rhodes,60,2,2,6334fa2a-8b4b-47e7-a451-5ae01754bf08,249.04,0,True,False,True
2,3,2,Angie Henderson,64,0,0,61a66444-e2af-4629-9efb-336e2f546033,50.31,1,True,True,False
3,4,2,Daniel Wagner,35,4,0,0b6c03c8-721e-4419-afc3-e6495e911b91,235.20,1,True,False,False
4,5,0,Cristian Santos,70,0,3,436e3c49-770e-49db-b092-d40143675d58,160.17,1,False,False,False

# Using MinMaxScaler

In [33]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [34]:
# Load Titanic dataset (you can replace the file path if necessary)
titanic_data = pd.read_csv("titanic.csv")

In [35]:
titanic_data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Survived
0,1,3,Allison Hill,male,17,4,2,43d75413-a939-4bd1-a516-b0d47d3572cc,144.08,Q,1
1,2,1,Noah Rhodes,male,60,2,2,6334fa2a-8b4b-47e7-a451-5ae01754bf08,249.04,S,0
2,3,3,Angie Henderson,male,64,0,0,61a66444-e2af-4629-9efb-336e2f546033,50.31,Q,1
3,4,3,Daniel Wagner,male,35,4,0,0b6c03c8-721e-4419-afc3-e6495e911b91,235.20,C,1
4,5,1,Cristian Santos,female,70,0,3,436e3c49-770e-49db-b092-d40143675d58,160.17,C,1

In [36]:
# Select the numerical features to normalize
numerical_columns = ['Age', 'Fare']  # You can add more numerical columns if necessary

In [37]:
numerical_columns

['Age', 'Fare']

In [38]:
# Initialize the MinMaxScaler
scaler = MinMaxScaler()

In [39]:
scaler

MinMaxScaler()

In [40]:
# Fit and transform the selected columns
titanic_data[numerical_columns] = scaler.fit_transform(titanic_data[numerical_columns])

In [42]:
titanic_data[numerical_columns].head()

        Age      Fare
0  0.205128  0.273726
1  0.756410  0.488035
2  0.807692  0.082265
3  0.435897  0.459776
4  0.884615  0.306579

In [44]:
# Display the normalized data
titanic_data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Survived
0,1,3,Allison Hill,male,0.205128,4,2,43d75413-a939-4bd1-a516-b0d47d3572cc,0.273726,Q,1
1,2,1,Noah Rhodes,male,0.756410,2,2,6334fa2a-8b4b-47e7-a451-5ae01754bf08,0.488035,S,0
2,3,3,Angie Henderson,male,0.807692,0,0,61a66444-e2af-4629-9efb-336e2f546033,0.082265,Q,1
3,4,3,Daniel Wagner,male,0.435897,4,0,0b6c03c8-721e-4419-afc3-e6495e911b91,0.459776,C,1
4,5,1,Cristian Santos,female,0.884615,0,3,436e3c49-770e-49db-b092-d40143675d58,0.306579,C,1

# Create New Feautures

In [48]:
# Assuming you have loaded the Titanic dataset into a pandas DataFrame called df
df = pd.read_csv('titanic.csv')

In [49]:
df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Survived
0,1,3,Allison Hill,male,17,4,2,43d75413-a939-4bd1-a516-b0d47d3572cc,144.08,Q,1
1,2,1,Noah Rhodes,male,60,2,2,6334fa2a-8b4b-47e7-a451-5ae01754bf08,249.04,S,0
2,3,3,Angie Henderson,male,64,0,0,61a66444-e2af-4629-9efb-336e2f546033,50.31,Q,1
3,4,3,Daniel Wagner,male,35,4,0,0b6c03c8-721e-4419-afc3-e6495e911b91,235.20,C,1
4,5,1,Cristian Santos,female,70,0,3,436e3c49-770e-49db-b092-d40143675d58,160.17,C,1

In [50]:
# Feature 1: Family Size (SibSp + Parch + 1)
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1

In [52]:
df['FamilySize'].head()

0    7
1    5
2    1
3    5
4    4
Name: FamilySize, dtype: int64

In [53]:
# Feature 2: Is Alone (1 if FamilySize == 1, else 0)
df['IsAlone'] = df['FamilySize'].apply(lambda x: 1 if x == 1 else 0)

In [54]:
df['IsAlone'].head()

0    0
1    0
2    1
3    0
4    0
Name: IsAlone, dtype: int64

In [62]:
# Feature 3: Age Group
df['AgeGroup'] = pd.cut(df['Age'], bins=[0, 12, 19, 60, float('inf')], labels=['Child', 'Teenager', 'Adult', 'Senior'])

In [64]:
df['AgeGroup'].head()

0    Teenager
1       Adult
2      Senior
3       Adult
4      Senior
Name: AgeGroup, dtype: category
Categories (4, object): ['Child' < 'Teenager' < 'Adult' < 'Senior']

In [65]:
# Feature 4: Fare per Person (Fare divided by FamilySize)
df['FarePerPerson'] = df['Fare'] / df['FamilySize']

In [66]:
df['FarePerPerson'].head()

0    20.582857
1    49.808000
2    50.310000
3    47.040000
4    40.042500
Name: FarePerPerson, dtype: float64

In [67]:
# Feature 5: Embarked Mode (One-hot encoding for Embarked)
df['Embarked_C'] = (df['Embarked'] == 'C').astype(int)
df['Embarked_Q'] = (df['Embarked'] == 'Q').astype(int)
df['Embarked_S'] = (df['Embarked'] == 'S').astype(int)

In [69]:
df['Embarked_C'].head()

0    0
1    0
2    0
3    1
4    1
Name: Embarked_C, dtype: int32

In [70]:
df['Embarked_Q'].head()

0    1
1    0
2    1
3    0
4    0
Name: Embarked_Q, dtype: int32

In [73]:
df['Embarked_S'].head()

0    0
1    1
2    0
3    0
4    0
Name: Embarked_S, dtype: int32

In [74]:
# Feature 6: Interaction between Age and Pclass
df['Age_Pclass_Interaction'] = df['Age'] * df['Pclass']

In [76]:
df['Age_Pclass_Interaction'].head()

0     51
1     60
2    192
3    105
4     70
Name: Age_Pclass_Interaction, dtype: int64

In [77]:
# Feature 07: Fare Binned (Categorizing Fare into Low, Medium, High)
df['FareBin'] = pd.cut(df['Fare'], bins=[0, 10, 50, float('inf')], labels=['Low', 'Medium', 'High'])

In [78]:
df['FareBin'].head()

0    High
1    High
2    High
3    High
4    High
Name: FareBin, dtype: category
Categories (3, object): ['Low' < 'Medium' < 'High']

In [80]:
# Feature 8: Interaction between Pclass and Sex
df['Pclass_Sex'] = df['Pclass'] * (df['Sex'] == 'male').astype(int)

In [81]:
df['Pclass_Sex'].head()

0    3
1    1
2    3
3    3
4    0
Name: Pclass_Sex, dtype: int64

# Extract Title From The Passenger Name

In [101]:
import pandas as pd
import re

# Sample Titanic dataset
df = pd.read_csv('titanic.csv')

# Function to extract title
def extract_title(name):
    title = re.search(r'([A-Za-z]+)\.', name)  # Search for any word followed by a period
    return title.group(1) if title else None  # If found, return the title

# Apply the function to the 'Name' column to extract the title
df['Title'] = df['Name'].apply(extract_title)

# Display the updated dataframe
print(df[['Name', 'Title']].head())

              Name Title
0     Allison Hill  None
1      Noah Rhodes  None
2  Angie Henderson  None
3    Daniel Wagner  None
4  Cristian Santos  None

# Create Family Size Feature

In [98]:
import pandas as pd

# Sample Titanic dataset
# df = pd.read_csv('titanic.csv')

# Create the 'FamilySize' feature by combining 'SibSp' and 'Parch' and adding 1 (for the passenger)
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1

# Display the updated dataframe with 'FamilySize'
print(df[['SibSp', 'Parch', 'FamilySize']].head())

In [99]:
df['FamilySize'].head()

0    7
1    5
2    1
3    5
4    4
Name: FamilySize, dtype: int64

In [100]:
# Display the new column
print(df[['SibSp', 'Parch', 'FamilySize']].head())

   SibSp  Parch  FamilySize
0      4      2           7
1      2      2           5
2      0      0           1
3      4      0           5
4      0      3           4